title: Rizqi Prima # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  First description Rizqi 
  <br><br>
  Second description Rizqi
  <br><br>
  <a href="https://www.linkedin.com/in/rizqiprima/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
